site_name: PathFinder
theme:
  # name: material
  # name: simple-blog
  name: terminal
  palette: dark

nav:
  - Home: index.md
  - Meet the Team: team.md
  - Project:
      - Overview: project/project.md
      - Mechanical: project/meche.md
      - Software & Firmware: project/software_firmware.md
  - Download!: download.md

plugins:
  # - gallery:
  #     examples_dirs: docs/examples # path to your example scripts
  #     gallery_dirs: docs/generated/gallery # where to save generated gallery

  - search # make sure the search plugin is still enabled

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - toc:
      baselevel: "1"
      toc_depth: "3"

extra:
  generator: false
  # logo: assets/img/avatar_me_plip.png
